# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0011_auto_20170321_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 10, 59, 22, 178897, tzinfo=utc)),
        ),
    ]
