# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0013_auto_20170321_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 11, 3, 54, 917909, tzinfo=utc)),
        ),
    ]
